//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:03:18 PM CDT 
//


package com.epsilon.employee.service.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Child complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Child">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stdno" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="childname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Child", propOrder = {
    "stdno",
    "childname"
})
public class Child {

    protected int stdno;
    @XmlElement(required = true)
    protected String childname;

    /**
     * Gets the value of the stdno property.
     * 
     */
    public int getStdno() {
        return stdno;
    }

    /**
     * Sets the value of the stdno property.
     * 
     */
    public void setStdno(int value) {
        this.stdno = value;
    }

    /**
     * Gets the value of the childname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildname() {
        return childname;
    }

    /**
     * Sets the value of the childname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildname(String value) {
        this.childname = value;
    }

}
